### ISSUE TITLE
bug in devseed seeder?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#102]
```
        $count_query = $query;
        $count_query->countQuery()->execute()->fetchField();
        if ($count_query === 0) {
            return factory($table)->create($factory_array);
        }
        if ($count_query === 1) {
            return $query->execute()->fetchObject();
        }
        throw new Exception("Error creating object for: ".$table.".\n Array supplied matches ".$count_query." results, must match 1.");
    }
```

im pretty sure we already fixed this but maybe we lost the fix.  Note $count_query is checked, NOT $count).  ie should instead be ` $count =        $count_query->countQuery()->execute()->fetchField();`

**Comment by almasaeed2010** [comment]
Also, let's remember to cast to `int`

```
 $count = (int) $count_query->countQuery()->execute()->fetchField();
```

**Comment by almasaeed2010** [comment]
This is fixed on master. Is there a way for us to write tests for this class?

**Comment by bradfordcondon** [comment]
> Is there a way for us to write tests for this class?

I think thi biggest hurdle is its all commented out in the stub.  Can we re visit that?  IE have seed not run all seeders?

Assuming we overcome that, then yeah its very testable by just having a module install testsuite and run the seeder then check the database for each content type.

**Comment by bradfordcondon** [comment]
OK we're all fixed now.

So we **could** add unit testing for the devseed seeder- install tripal, tripal_analysis_expression, tripal_analysis_interpro, and run the seeder, ensure data was loaded.  If we want to its a seperate issue- i think this issue is resolved.
