### ISSUE TITLE
Documentation for use of faker

### ISSUE THREAD

**Issue by laceysanderson** [statonlab/TripalTestSuite#103]
Since Faker is the accepted way to create fake data for tests, factories and database seeders, it would be great to have an example somewhere in the TripalTestSuite documentation. Just something like the following. I would submit a PR but I still don't have the hang of ReadTheDocs and am not sure where you would want it.

This would be great to reference when writing tests as right now I find myself constantly looking up my old tests when I need to use faker.

### Generating Fake variables for use in testing
The recommended method to create fake values for use in testing is to use the PHP Faker library by @fzaninotto: https://github.com/fzaninotto/Faker. To use this library in your Tripal tests, simply include it at the top of the class:
```
use StatonLab\TripalTestSuite\DBTransaction;
use StatonLab\TripalTestSuite\TripalTestCase;
use Faker\Factory;

class ExampleTest extends TripalTestCase {
``` 

Then instantiate it in your test method and create fake data using one of the various methods available through the library. 

```php
public function testExample() {

    // Generate a fake version.
    $faker = Factory::create();
    $version = $faker->randomFloat(2, 1, 5);

}
```

More more information on what is provided by hte fake library, check out their documentation here: [github.com/fzaninotto/Faker](https://github.com/fzaninotto/Faker/blob/master/readme.md)

**Comment by bradfordcondon** [comment]
Yeah i use $faker sometimes too beyond factories.  However it isnt really Tripal Test suite so much as a handy PHP library thats good for testing.

Maybe we can have a guide section and/or "Tips and Tricks" section.

**Comment by laceysanderson** [comment]
Exactly, but it's documentation that's currently not easily found. I like the idea of a "Tips or Tricks" section :-)

**Comment by laceysanderson** [comment]
It's been merged and it Awesome -Thank you!
