### ISSUE TITLE
out of the box does not pass tests

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#15]
https://travis-ci.org/statonlab/tripal_analysis_kegg

two build issues:

* enabling the module fails (?) for both kegg and ssr.
* No tests in test classes/extra test classes read in (see below)

```
WW                                                                  2 / 2 (100%)
Time: 31 ms, Memory: 4.00MB
There were 2 warnings:
1) Warning
No tests found in class "StatonLab\TripalTestSuite\TripalTestCase".
2) Warning
No tests found in class "Tests\MyTest".
WARNINGS!
Tests: 2, Assertions: 0, Warnings: 2.
The command "docker exec -it tripal bash -c 'cd /var/www/html/sites/all/modules/custom/tripal_analysis_kegg/ &&composer install && DRUPAL_ROOT="/var/www/html" ./vendor/bin/phpunit'" exited with 1.```

**Comment by bradfordcondon** [comment]
adding `require __DIR__.'/../vendor/autoload.php';` to bootstrap.php isnt enough. to work locally

**Comment by almasaeed2010** [comment]
Could you test this again please?

My tests run fine locally but I didn't test on travis

**Comment by bradfordcondon** [comment]
- [ ] out of box tests work

- [ ] out of box travis works

**Comment by bradfordcondon** [comment]
Travis build fails on module enable for all modules i've tested so far.  no error.  why?

**Comment by bradfordcondon** [comment]
to get to the bottom of thise i looked at tripal_curator, which actually enables tripal_biomaterial for its test environment.

https://travis-ci.org/statonlab/tripal_curator/builds/357001755?utm_source=slack&utm_medium=notification

passes!

ok, so lets enable tripal_analysis_expression instead?

https://travis-ci.org/statonlab/tripal_curator/builds/357003729?utm_source=slack&utm_medium=notification

fails.

**Comment by almasaeed2010** [comment]
fixed
