### ISSUE TITLE
dbseeders

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#17]
https://github.com/tripal/tripal/issues/311
A seeder base class. 

>Yeah add a Seeds folder in the tests folder where we auto detect and load the seeders for use in setup and teardown fns

We can leave it up to tripal core, or to the devseed project, to provide the seeders.
A test class just says which seeders it requires and the db gets seeded prior to each test.

**Comment by almasaeed2010** [comment]
Implemented.
