### ISSUE TITLE
php 5 support

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#26]
We should consider how to support php 5 for the developers who cannot or will not upgrade to php 7

**Comment by laceysanderson** [comment]
Trying would be appreciated :-) I'm not quite ready to upgrade PHP on my system but would love to get started with testing **fingers crossed** I hope it's not to much effort on your part!

**Comment by almasaeed2010** [comment]
It's literally 1 more line in composer.json so i'll create it in a few hours and run some tests in php5 environment

**Comment by almasaeed2010** [comment]
Support for PHP5 is now available. Please let me know if you encounter any issues.

Thanks!
