### ISSUE TITLE
testing importers

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#44]
```
namespace tripal_cmap_loader;


class CmapImporter extends TripalImporter {
```

So im trying to test my importer.  I am namespacing my importer like so:

then in my test:
```
namespace Tests;

use StatonLab\TripalTestSuite\TripalTestCase;
use tripal_cmap_loader;

/**
 * Class ExampleTest
 *
 * Note that test classes must have a suffix of Test.php and the filename
 * must match the class name.
 *
 * @package Tests
 */
class CmapImporterTest extends TripalTestCase
{
    public function testInit()
    {
$this->assertTrue(TRUE);

$importer = new tripal_cmap_loader\CmapImporter();
```
I keep getting `Error: Class 'tripal_cmap_loader\CmapImporter' not found` with a variety of namespace combinations.

**Comment by bradfordcondon** [comment]
OK i think i see the problem:
Importers are not included in the code manually, whereas TripalImporter (base class) is.

however adding `include_once('../includes/TripalImporter/CmapImporter.inc');` below my namespace in the test gives me this error:

`PHP Fatal error:  Class 'Tests\TripalTestCase' not found in /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_cmap_loader/tests/CmapImporterTest.php on line 15`

**Comment by almasaeed2010** [comment]
I think it's worth mentioning common pitfalls in the guide. So, we can write about having to include your classes before using them in name-spaced tests.

One option is to `use` the class explicitly:
```php
use CmapImporter;

$loader = new CmapImporter()
```

The other is to include the full namespace, which in this case is the global space `\`:
```php
$loader = new \CmapImporter();
```

**Comment by bradfordcondon** [comment]
actually i dont think that snippet will work because cmapImporter isn't included anywhere in Drupal (like how fields aren't, either...).  Needs `require_once(__DIR__.'/../includes/TripalImporter/CmapImporter.inc');`

**Comment by almasaeed2010** [comment]
Yeah I meant to ask about that. Why aren't they included? When does Tripal load them?

**Comment by almasaeed2010** [comment]
Also to stick to "drupal standards", we could recommend [`module_load_include`](https://api.drupal.org/api/drupal/includes%21module.inc/function/module_load_include/7.x)

**Comment by bradfordcondon** [comment]
So I've now written tests for a bunch of importers, its pretty easy: you just provide two arrays to the importer's run: one array containing the file to import (if applicable), the other with the run options that would have been passed from $form_state('#values').

I should write up a quick use case for documentation.

**Comment by bradfordcondon** [comment]
The Devseed seeder provides a great example on how to run all importers within test suite.
