### ISSUE TITLE
upgrade instructions

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#61]
we need simple upgrade instructions in the README.

**Comment by bradfordcondon** [comment]
is it just ` composer update` ? hahah

**Comment by almasaeed2010** [comment]
Well it depends if you are upgrading a major version or a patch. See https://getcomposer.org/doc/articles/versions.md for full instructions.

**Comment by almasaeed2010** [comment]
Added in #66
