### ISSUE TITLE
no analysis factory despite devseedSeeder using it

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#74]
In the past you've said you want factories only available as gists but im going to again lobby that we (me) provide factories for all base chado tables.

**Comment by almasaeed2010** [comment]
I think it’s fine to have factories for the major tables. But prop tables and relationships don’t make much sense to me honestly

**Comment by bradfordcondon** [comment]
i think prop tables could be handy but i dont think they'll be common enough that it matters (creating your own is no problem).

relationships would be weird as a factory.

**Comment by bradfordcondon** [comment]
```php
/** @see  StatonLab\TripalTestSuite\Database\Factory::define() */
Factory::define('chado.analysis', function (Faker\Generator $faker) {
  return [
    'name' => $faker->name,
    'description' => $faker->name,
    'program' => $faker->unique()->name,
    'programversion' => $faker->unique()->name,
    'sourcename' => $faker->unique()->name,
    'algorithm' => $faker->name,
    'sourcename' => $faker->name,
    'sourceversion' => $faker->name,
    'sourceuri' => $faker->name,
    // 'timeexecuted' => $faker->time()// needs to match 2018-03-23 15:08:00.000000
  ];
});
```

**Comment by bradfordcondon** [comment]
## Preexisting
* db
* cv
* dbxref
* feature
* organism
* cvterm

## To add
Major base tables. The tables we thoroughly ignore i dont think we need to include.

### should add

- [x] analysis
- [ ] assay
- [ ] biomaterial
- [ ] contact
- [ ] featuremap
- [ ] featureloc
- [ ] featurepos
- [ ] library
- [ ] project
- [ ] protocol
- [ ] pub


### meh
- [ ] stock
- [ ] phenotype
- [ ] genotype
- [ ] featurerange (maybe not this one since we aren't fans of it?)
- [ ] cell_line


### other thoughts

I also left out the nd module since theres some overlap that i find confusing nd_protocol vs protocol for example.

**Comment by bradfordcondon** [comment]
Featureloc not added because of search_path issues.  see #77
