### ISSUE TITLE
search path needs some finesse

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#77]
```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  function create_point(integer, bigint) does not exist
LINE 1: SELECT box (create_point(0, $1), create_point($2,500000000))
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))
CONTEXT:  SQL function "boxrange" during inlining
```

currently get this error when running  the ` 'chado.featureloc',` factory,

probably need to `set search_path to public, chado;` which we can do manually or better run the trpal function that sets the searchpath for you.

**Comment by almasaeed2010** [comment]
Instead of using `chado_set_active()`. Did you try `db_query('set search_path to public, chado');`?

**Comment by bradfordcondon** [comment]
doing `chado_set_active('chado');` appears to work.  can we do that instead?

**Comment by bradfordcondon** [comment]
from stephen:

`$prev_db = chado_set_active('chado')`
`chado_set_active($prev_db)`

we need to set it back to teh way it was at the start, on decontsruction of the class

**Comment by almasaeed2010** [comment]
Since this is not always needed, I think the user should define this in their own `setUp` or `setUpBeforeClass` methods. Should we document this somewhere? Or is that more of a tripal thing that testsuite's?

**Comment by bradfordcondon** [comment]
I guess its more of a tirpal thing.  its just needed for that one table.  We can add an in-line code comment that you need to use chado_set_active for that particular factory
