### ISSUE TITLE
Use readthedocs 

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/TripalTestSuite#85]
Uodate docs to use readthedocs

**Comment by bradfordcondon** [comment]
* I think the README is too barebones.  Github should still looks sort of nice.
* Should I make suggestions in a seperate branch via pR or push directly to your RTD branch?

**Comment by almasaeed2010** [comment]
I went ahead and published what I got to read the docs.

Please feel free to edit and publish if you find anything.
