### ISSUE TITLE
Installation Docs

### ISSUE THREAD

**Issue by spficklin** [statonlab/TripalTestSuite#97]
So the instructions for installation confused me a bit.  Perhaps a slight re-organization would help?

On this page it talks about .env and .travis.yml files:
https://tripaltestsuite.readthedocs.io/en/latest/installation.html

But  I don't see instructions for the .env file until the very end of the document.  Should it go in a subsection of the installation?

**Comment by bradfordcondon** [comment]
yeah.  Setup needs to at the very least include a reference to the .env/example.env file and link to

https://tripaltestsuite.readthedocs.io/en/latest/environment.html

**Comment by bradfordcondon** [comment]
@spficklin i've updated the documentation in several ways.  Better?

**Comment by bradfordcondon** [comment]
@spficklin please let me know if you have additional recommendations, thank you!

**Comment by spficklin** [comment]
Yes I think so.  I don't have time to look over it too carefully, but next time I do an install I'll run through it again and let you know!

**Comment by bradfordcondon** [comment]
no worries, thanks again for the feedback
